apiVersion: v1
kind: Service
metadata:
  name: mstream
spec:
  ports:
  - port: 80
    name: http
  clusterIP: None
  selector:
    app: mstream
---
apiVersion: v1
kind: Service
metadata:
  name: mstream-lb
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: mstream