apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mstream
  labels:
    app: mstream
spec:
  selector:
    matchLabels:
      app: mstream
  serviceName: mstream
  replicas: 1
  template:
    metadata:
      labels:
        app: mstream
    spec:
      containers:
        - name: mstream
          image: linuxserver/mstream:5.12.2
          ports:
            - containerPort: 3000
              name: web
          volumeMounts:
            - name: music-storage
              mountPath: /music
  volumeClaimTemplates:
    - metadata:
        name: music-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
